import dash_bootstrap_components as dbc
from dash import html

from func import create_card

layout = dbc.Container(
    [
        dbc.Row(
            [
                dbc.Col(
                    html.A(
                        [html.Div(create_card("atlanta-hawks"))],
                        href="/atlanta_hawks",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("boston-celtics"))],
                        href="/boston_celtics",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("brooklyn-nets"))],
                        href="/brooklyn_nets",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("charlotte-hornets"))],
                        href="/charlotte_hornets",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("chicago-bulls"))],
                        href="/chicago_bulls",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("cleveland-cavaliers"))],
                        href="/cleveland_cavaliers",
                    )
                ),
            ],
            style={"margin-bottom": "1rem", "margin-top": "1rem"},
        ),
        dbc.Row(
            [
                dbc.Col(
                    html.A(
                        [html.Div(create_card("dallas-mavericks"))],
                        href="/dallas_mavericks",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("denver-nuggets"))],
                        href="/denver_nuggets",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("detroit-pistons"))],
                        href="/detroit_pistons",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("golden-state-warriors"))],
                        href="/golden_state_warriors",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("houston-rockets"))],
                        href="/houston_rockets",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("indiana-pacers"))],
                        href="/indiana_pacers",
                    )
                ),
            ],
            style={"margin-bottom": "1rem", "margin-top": "1rem"},
        ),
        dbc.Row(
            [
                dbc.Col(
                    html.A(
                        [html.Div(create_card("los-angeles-clippers"))],
                        href="/los_angeles_clippers",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("los-angeles-lakers"))],
                        href="/los_angeles_lakers",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("memphis-grizzlies"))],
                        href="/memphis_grizzlies",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("miami-heat"))],
                        href="/miami_heat",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("milwaukee-bucks"))],
                        href="/milwaukee_bucks",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("minnesota-timberwolves"))],
                        href="/minnesota_timberwolves",
                    )
                ),
            ],
            style={"margin-bottom": "1rem", "margin-top": "1rem"},
        ),
        dbc.Row(
            [
                dbc.Col(
                    html.A(
                        [html.Div(create_card("new-orleans-pelicans"))],
                        href="/new_orleans_pelicans",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("new-york-knicks"))],
                        href="/new_york_knicks",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("oklahoma-city-thunder"))],
                        href="/oklahoma_city_thunder",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("orlando-magic"))],
                        href="/orlando_magic",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("philadelphia-76ers"))],
                        href="/philadelphia_76ers",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("phoenix-suns"))],
                        href="/phoenix_suns",
                    )
                ),
            ],
            style={"margin-bottom": "1rem", "margin-top": "1rem"},
        ),
        dbc.Row(
            [
                dbc.Col(
                    html.A(
                        [html.Div(create_card("portland-trail-blazers"))],
                        href="/portland_trail_blazers",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("sacramento-kings"))],
                        href="/sacramento_kings",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("san-antonio-spurs"))],
                        href="/san_antonio_spurs",
                    )
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("toronto-raptors"))],
                        href="/toronto_raptors",
                    )
                ),
                dbc.Col(
                    html.A([html.Div(create_card("utah-jazz"))], href="/utah_jazz")
                ),
                dbc.Col(
                    html.A(
                        [html.Div(create_card("washington-wizards"))],
                        href="/washington_wizards",
                    )
                ),
            ],
            style={"margin-bottom": "1rem", "margin-top": "1rem"},
        ),
    ],
    className="LogoHolder",
)
